### ISSUE TITLE
no page at root of website

### ISSUE THREAD

**Issue by aut0maticjack** [s-20/unnamed#3]
not sure if this is because you are avoiding external scrutiny or just you haven't bothered to set up an actual front page, but going to " https://s-20.github.io/ " gets me a 404 error.

**Comment by s-20** [comment]
There's nothing there because I haven't set up a page for all my repos, just the two I've worked on (which will be down to one when I get rid of the old one). My plan is to eventually have a page there, but for now I'm directing people to https://s-20.github.io/unnamed/ instead.
