### ISSUE TITLE
Add link to github repository

### ISSUE THREAD

**Issue by aut0maticjack** [s-20/unnamed#4]
Your wiki pages should have a link to this repository on them, so that I don't have to take the extra step of getting here through a google search when I want to harass you with more new issues ;)
Right next to the CC license logo might not be a bad place... Pretty sure Github already has some boilerplate you can use for this...

**Comment by s-20** [comment]
Added. There's a link on the page that opens when you go directly to the site, but once that page is gone there's no way to bring it back without leaving and returning, so a permanent link is a much better idea!
